# version: "3.8"
services:
  backend:
    build: ./backend
    container_name: pong_backend
    environment:
      - DJANGO_SETTINGS_MODULE=django_server.settings
      - DEBUG=True
    restart: unless-stopped
    networks:
      - pongnet
    expose:
      - "3000"
    ports:
      - "3000:3000"

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pong_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pongnet
    environment:
      - VITE_BACKEND_URL=http://backend:3000

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: pong_nginx
  #   depends_on:
  #   - backend
  #   ports:
  #   - "8080:80"
  #   volumes:
  #   - ./frontend/dist:/usr/share/nginx/html:ro
  #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   networks:
  #   - pongnet

networks:
  pongnet:
    driver: bridge